name: Build Docker Image

on:
  workflow_dispatch:
jobs:
  push_to_registry:
    runs-on: ubuntu-20.04
    name: Build and Push Peaq Docker Image to Docker Hub
    steps:
      - name: "Free Disk Space (insightsengineering/disk-space-reclaimer)"
        uses: insightsengineering/disk-space-reclaimer@v1.1.0
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: ${{ secrets.DOCKER_REG_PARACHAIN}}
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=ref,event=tag

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          file: scripts/Dockerfile
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}